// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgOlgH6oxCw5Ie3OhRHwIXTJQykKg7DD4',
    appId: '1:335958231722:web:af4e43bf467b9b328e9ed3',
    messagingSenderId: '335958231722',
    projectId: 'salon-app-ff4e1',
    authDomain: 'salon-app-ff4e1.firebaseapp.com',
    storageBucket: 'salon-app-ff4e1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQo9H0m5nbUA64BCD-yHn7FQXoM3iUmKE',
    appId: '1:335958231722:android:f5e796b39776e32a8e9ed3',
    messagingSenderId: '335958231722',
    projectId: 'salon-app-ff4e1',
    storageBucket: 'salon-app-ff4e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIg9693V9mZQjo8I1wuu3YdT68XWcr0_Y',
    appId: '1:335958231722:ios:173a745224d997448e9ed3',
    messagingSenderId: '335958231722',
    projectId: 'salon-app-ff4e1',
    storageBucket: 'salon-app-ff4e1.appspot.com',
    iosBundleId: 'com.google.firebase.presents.newProject',
  );
}
